name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  rector:
    name: Rector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Run Rector (dry-run)
        run: vendor/bin/rector process --dry-run --ansi

  linter:
    name: PHP Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Run Linter
        run: find . -type f -name "*.php" -not -path "./vendor/*" -exec php -l {} \;

  larastan:
  
    name: Larastan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Run Larastan (static analysis)
        run: vendor/bin/phpstan analyse --no-progress